name: update main version

# Re-tags the latest main version, using the latest tag's major version
# Examples: `v1.2.0 -> v1` or `v2.9.0 -> v2`
# Triggers: after a release is published, or manually dispatched
# Similar to: https://github.com/actions/checkout/blob/main/.github/workflows/update-main-version.yml

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      target:
        description: |
          The tag, ref, or latest full version to use. Example: v1.2.1
        required: true
      version:
        description: |
          The major version to update. Example: v1
        required: true
        default: 'v1'

env:
  TARGET: ${{ github.event.inputs.target || github.event.release.tag_name }}

jobs:
  update-main-version:
    name: Update main version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@main
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Config git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "226837+jonlabelle@users.noreply.github.com"

      - name: Auto-tag latest major version with ${{ env.TARGET }}
        if: ${{ github.event_name != 'workflow_dispatch' }}
        run: |
          if [[ "${TARGET}" =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            MAJOR_VER="$(echo "${TARGET}" | cut -d. -f1)"
            if [[ "${TARGET}" != "${MAJOR_VER}" ]]; then
              git tag -f "${MAJOR_VER}" "${TARGET}"
              git push origin "${MAJOR_VER}" --force
              echo "::notice title=Main version tagged::Tagged "${TARGET}" with "${MAJOR_VER}""
            else
              echo "::warning title=Already tagged::Target is already tagged with "${MAJOR_VER}". Nothing to do."
            fi
          else
            echo "::warning title=Invalid semver::"${TARGET}" is not a valid semver. Nothing to do."
          fi

      - name: Tag new target
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          MAJOR_VER: ${{ github.event.inputs.version }}
        run: git tag -f "${MAJOR_VER}" "${TARGET}"

      - name: Push new tag
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          MAJOR_VER: ${{ github.event.inputs.version }}
        run: |
          git push origin "${MAJOR_VER}" --force
          echo "::notice title=Main version tagged::Tagged "${TARGET}" with "${MAJOR_VER}""
